import { Book } from '@koinsight/common/types/book';
import { Knex } from 'knex';

const books: Partial<Book>[] = [
  {
    id: 1,
    title: 'Mistborn: The Final Empire',
    authors: 'Brandon Sanderson',
    notes: 5,
    last_open: 1712890000,
    highlights: 11,
    pages: 541,
    series: 'Mistborn',
    language: 'en',
    md5: null,
    total_read_time: 38600,
    total_read_pages: 358,
  },
  {
    id: 2,
    title: 'The Name of the Wind',
    authors: 'Patrick Rothfuss',
    notes: 3,
    last_open: 1712564000,
    highlights: 8,
    pages: 662,
    series: 'The Kingkiller Chronicle',
    language: 'en',
    md5: null,
    total_read_time: 44200,
    total_read_pages: 411,
  },
  {
    id: 3,
    title: 'A Game of Thrones',
    authors: 'George R. R. Martin',
    notes: 6,
    last_open: 1712208000,
    highlights: 17,
    pages: 694,
    series: 'A Song of Ice and Fire',
    language: 'en',
    md5: null,
    total_read_time: 62300,
    total_read_pages: 496,
  },
  {
    id: 4,
    title: 'The Way of Kings',
    authors: 'Brandon Sanderson',
    notes: 9,
    last_open: 1712456000,
    highlights: 20,
    pages: 1007,
    series: 'The Stormlight Archive',
    language: 'en',
    md5: null,
    total_read_time: 79200,
    total_read_pages: 486,
  },
  {
    id: 5,
    title: 'The Fellowship of the Ring',
    authors: 'J.R.R. Tolkien',
    notes: 2,
    last_open: 1712777000,
    highlights: 7,
    pages: 479,
    series: 'The Lord of the Rings',
    language: 'en',
    md5: null,
    total_read_time: 41800,
    total_read_pages: 264,
  },
  {
    id: 6,
    title: 'The Two Towers',
    authors: 'J.R.R. Tolkien',
    notes: 4,
    last_open: 1712809000,
    highlights: 9,
    pages: 415,
    series: 'The Lord of the Rings',
    language: 'en',
    md5: null,
    total_read_time: 36200,
    total_read_pages: 302,
  },
  {
    id: 7,
    title: 'The Last Wish',
    authors: 'Andrzej Sapkowski',
    notes: 3,
    last_open: 1712688000,
    highlights: 10,
    pages: 384,
    series: 'The Witcher',
    language: 'en',
    md5: null,
    total_read_time: 28000,
    total_read_pages: 289,
  },
  {
    id: 8,
    title: 'Hyperion',
    authors: 'Dan Simmons',
    notes: 7,
    last_open: 1712266000,
    highlights: 14,
    pages: 482,
    series: 'Hyperion Cantos',
    language: 'en',
    md5: null,
    total_read_time: 41500,
    total_read_pages: 377,
  },
  {
    id: 9,
    title: 'The Martian',
    authors: 'Andy Weir',
    notes: 2,
    last_open: 1712119000,
    highlights: 10,
    pages: 369,
    series: null,
    language: 'en',
    md5: null,
    total_read_time: 24000,
    total_read_pages: 312,
  },
  {
    id: 10,
    title: 'Foundation',
    authors: 'Isaac Asimov',
    notes: 3,
    last_open: 1712305000,
    highlights: 12,
    pages: 244,
    series: 'Foundation Series',
    language: 'en',
    md5: null,
    total_read_time: 36900,
    total_read_pages: 283,
  },
];

export async function seed(knex: Knex): Promise<void> {
  await knex('book').del();
  await knex('book').insert(books);
}
